Add section 6 changes

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,16 +1,3 @@
-#!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
-
-#local_branch_name="$(git rev-parse --abbrev-ref HEAD)"
-
-#valid_branch_regex='^((hotfix|bugfix|feature)\/[a-zA-Z0-9\-]+)$'
-
-#message="Please check your branch name."
-
-#if [[ ! $local_branch_name =~ $valid_branch_regex ]]; then
-#    echo -e "\033[0;31m$message"
-#    exit 1
-#fi
-
-#exit 0
-
+#!/bin/sh
+command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'pre-push' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks').\n"; exit 2; }
+git lfs pre-push "$@"
